

blend.clrwl_gbuffers = off
blend.clrwl_gbuffers_additive = off
blend.clrwl_gbuffers_lightning = off
blend.clrwl_gbuffers_glint = off
blend.clrwl_gbuffers_translucent = off
blend.clrwl_gbuffers_damagedblock = off

oit = false
